services:
  all-medical:
    build:
      context: ./all-medical/all-medical
    image: ${DOCKERHUB_USERNAME}/all-medical:latest
    ports:
      - "5003:5003"
    env_file:
      - ./all-medical/.env

  create-medical:
    build:
      context: ./create-medical/create-medical
    image: ${DOCKERHUB_USERNAME}/create-medical:latest
    ports:
      - "5001:5001"
    env_file:
      - ./create-medical/.env

  delete-medical:
    build:
      context: ./delete-medical/delete-medical
    image: ${DOCKERHUB_USERNAME}/delete-medical:latest
    ports:
      - "5005:5005"
    env_file:
      - ./delete-medical/.env

  latest-medical:
    build:
      context: ./latest-medical/latest-medical
    image: ${DOCKERHUB_USERNAME}/latest-medical:latest
    ports:
      - "5004:5004"
    env_file:
      - ./latest-medical/.env

  update-medical:
    build:
      context: ./update-medical/update-medical
    image: ${DOCKERHUB_USERNAME}/update-medical:latest
    ports:
      - "5002:5002"
    env_file:
      - ./update-medical/.env